### ISSUE TITLE
NameError: global name 'problem_code' is not defined

### ISSUE THREAD

**Issue by ghost** [himansurathi/Download-UVA-and-Codechef-files#2]
No internet Connection no host given.
When I execute downloadcodechef.py  It prints this 
{
No internet Connection no host given
NameError: global name 'problem_code' is not defined
..
}

**Comment by ghost** [comment]
Traceback (most recent call last):
  File "C:\Users\Varun\Downloads\UVA Codechef\Download-UVA-and-Codechef-files-master\downloadcodechef.py", line 137, in <module>
    main()
  File "C:\Users\Varun\Downloads\UVA Codechef\Download-UVA-and-Codechef-files-master\downloadcodechef.py", line 103, in main
    source_html= urllib2.urlopen(url).readlines()
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 429, in open
    req = meth(req)
  File "C:\Python27\lib\urllib2.py", line 1125, in do_request_
    raise URLError('no host given')
URLError: <urlopen error no host given>
